### ISSUE TITLE
Add rush % to character overview

### ISSUE THREAD

**Issue by GitDaskar** [star-ocean-anamnesiac/discord-anamnesiac#24]
Enhancement Request suggested by Kirino and six.  Up to you to make the call on whether we add it or not.  I don't personally think it needs to be.

IrohaToday at 10:19 AM
it doesn't show rush percentage, Dask?
weird

sixToday at 10:19 AM
that is weird
mama rush damage

DaskarToday at 10:19 AM
No, skill%s aren't shown at all

IrohaToday at 10:19 AM
report to Sei?

DaskarToday at 10:19 AM
I can suggest an enhancement.

**Comment by seiyria** [comment]
I think if I do anything - after discussion - what I'd do is add a line that shows rush % and element (or none, if no element)

I'm not sold on it either but the noise is minimal.
