### ISSUE TITLE
alias lightning to thunder

### ISSUE THREAD

**Issue by seiyria** [star-ocean-anamnesiac/discord-anamnesiac#44]

**Comment by eiyu** [comment]
Hi, I'm trying to solve this issue i don't know if i actually can solve it tho. but can you give more details about this issue. thanks

**Comment by seiyria** [comment]
Sure. In places like [this](https://github.com/star-ocean-anamnesiac/discord-anamnesiac/blob/master/commands/item.js#L32-L34) you'll need to add a case where `if(element === lightning) element = thunder` (to put it simply). You'll basically want to ctrl+f the codebase for any instance of element, and make sure the case is handled appropriately. Let me know if you need anything else!

**Comment by eiyu** [comment]
ok thanks, the assets is from your website so its a lil bit harder to work with than using an actual database. So i just want to confirm that when user trying to requests lightning the expect to give is lightning and thunder instances, and the otherwise when user trying to request thunder also gives thunder and lightning?

**Comment by seiyria** [comment]
so, there are no `thunder` items at all. the idea is to replace `lightning` with `thunder` for the users because when you do a fuzzy search for `light` it also brings up `lightning`. this would make it so any time `lightning` is encountered, it would display as `thunder` instead. when you search for `thunder` it would bring up what currently exists for `lightning`.

Hopefully that wasn't too confusing...

**Comment by eiyu** [comment]
I see , the fuzzyset is sure doing it's job 😆 . Ok i got it now.

**Comment by eiyu** [comment]
i think i can make it, i'm still testing my code. I'll let you know when I'm done. But i don't know if my code is like what you're expecting for
